version: "2"
services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
  
  backend:
    build: ./server/
    ports:
      - "3031:3031"
    volumes:
      - ./server:/usr/src/app
    depends_on: 
      - mongo

  frontend:
    build: ./client/
    ports:
      - "8081:8080"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

